### ISSUE TITLE
Good job making Travis do more than build... What about tests?

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-awesomebakery#11]
Great job using Travis to do more than just compile the code. 👍

Next step would be adding Unit Tests and automatically checking Coverage, and eventually Sonar.

The other groups will be expected to do this in soon too, at least one team has added Sonar: HBRS-MAAS/project-pieceofcake#6
@argenos.

**Comment by moriarty** [comment]
Regarding my previous comment: 

> and eventually Sonar.

The time has arrived. See #12

**Comment by element54** [comment]
Sonar integration is done. See #12

**Comment by element54** [comment]
Unit tests are covered by #14. Closing this one
