### ISSUE TITLE
Timing mechanism

### ISSUE THREAD

**Issue by element54** [HBRS-MAAS/project-awesomebakery#13]
For our simulation we need a timing mechanism (clock).

I suggest to have a single class (Timer, singleton) where components can register, access the current time and register to get notified at specific points in time.

What do you guys think? @azimme2s @mwiktorin

**Comment by mwiktorin** [comment]
Yes this sounds good.

**Comment by mwiktorin** [comment]
Time engine is changed and merged, #21
