### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by element54** [HBRS-MAAS/project-awesomebakery#14]
We should implement some unit tests that will also be used by travis to test our software instead of just compilation.

**Comment by mwiktorin** [comment]
I included the jade test library to our project on the testing branch, see 268c694932436bda4786117933b4b8482072f2e9
documentation can be found here http://jade.tilab.com/doc/tutorials/JADE_TestSuite.pdf

**Comment by element54** [comment]
Test libs are integrated. See #24

**Comment by moriarty** [comment]
I've opened similar issues for all groups.

HBRS-MAAS/project-awesomebakery#14
HBRS-MAAS/project-autobake#11
HBRS-MAAS/project-zarvis#7
HBRS-MAAS/project-pieceofcake#14
HBRS-MAAS/project-just_a_bakery#11
HBRS-MAAS/project-gabych#6

**Comment by element54** [comment]
Partially covered by #34

**Comment by moriarty** [comment]
👍 86% coverage

**Comment by argenos** [comment]
This is great!! 👍🏽
