### ISSUE TITLE
Add sonarcloud user to project

### ISSUE THREAD

**Issue by element54** [HBRS-MAAS/project-awesomebakery#16]
Hello @moriarty,

can you please add our sonarcloud user @sonarcube to this project? I cannot.

**Comment by moriarty** [comment]
I just did what I could from the mobile interface...

@argenos might be at her laptop if it didn’t work.

**Comment by moriarty** [comment]
@element54 I've assigned you back, if it works, close the issue.

**Comment by element54** [comment]
Seems to work

**Comment by moriarty** [comment]
👍 cool, if you have a pull request where it gives feedback in the pull request, please take a screenshot and tag me in the PR, I'd like to use it as an example.

https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

**Comment by argenos** [comment]
@element54 I have added the bot to your team now, not sure if it needs to accept the invitation somehow
