### ISSUE TITLE
Useful Unit Test Names and comments

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-awesomebakery#41]
Following a clear naming convention helps us quickly review your tests to check what has been implemented, and tested... This assumes the tests are doing useful things and doing what they say they are. So, the following test could be ```testFromJsonNotNullEqualsKneadingMachine001()``` ... java is a little verbose so maybe just ```testFromJsonEqualsKneadingMachine001()```.

https://github.com/HBRS-MAAS/project-awesomebakery/blob/4bb214f740cd793ced547a2dd24d488e68e982c5/src/test/java/org/awesomebakery/tests/model/KneadingMachineTest.java#L26-L31

https://dzone.com/articles/7-popular-unit-test-naming

Also, this unit test, depends on the contents of a file.
Considering the contents of the file, I would consider just keeping the string in the unit test, unless you're using them elsewhere. 

https://github.com/HBRS-MAAS/project-awesomebakery/blob/4bb214f740cd793ced547a2dd24d488e68e982c5/src/test/java/org/awesomebakery/tests/model/KneadingMachineTest.java#L21

@argenos we should open similar issues for other groups... But that would require checking and creating code samples for each group and can't be copied and pasted quickly.

So for now tag them all here, and I'll assume they get notified.
@HBRS-MAAS/autobake @HBRS-MAAS/breadnbeer @HBRS-MAAS/just_a_bakery @HBRS-MAAS/pieceofcake @HBRS-MAAS/zarvis @HBRS-MAAS/gabych 

This doesn't just help us now while reviewing your projects. When you're developing software after university, unit tests are there for a reason, to verify your code works, and sometimes through refactoring you break it- having useful names helps pinpoint what you broke and perhaps you know what/how/why just from a very descriptive name. The worst case, is when you no longer know what the test was suppose to test, and it doesn't have comments, use case documentation or a descriptive name.

**Comment by argenos** [comment]
@moriarty I think every team gets a notification, but just in case cc @HBRS-MAAS/ws17
